workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH #Executa se ocorrer um merge ou commit na main/dev

stages:
  - test
  - build
  - deploy

default:
  image: node:20.11

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

build:
  stage: build

  before_script:
    - npm ci

  script:
    - npm run build

  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
      - .next/cache/

deploy:
  stage: deploy

  before_script:
    - npm ci

  script:
    - npm i -g netlify-cli
    - netlify deploy --build --prod --message="$CI_COMMIT_MESSAGE"

  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
      - .next/cache/

